cars/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'cars#index'
  get '/cars' => 'cars#index', as:'cars'
  get '/cars/new' => 'cars#new', as: 'new_car'
  post '/cars' => 'cars#create'
  get '/cars/:id/edit' => 'cars#edit', as: 'edit_car'
  get '/cars/:id' => 'cars#show', as: 'car'
  patch '/cars/:id' => "cars#update"
  delete '/cars/:id' => "cars#destroy"

  #resources :cars


end

cars/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cars/app/models/car.rb
class Car < ApplicationRecord

  validates :make, presence: true
  validates :model, length: {minimum: 3}
  validates :mpg, numericality: {greater_than_or_equal_to: 0}
  validates :price, numericality: {greater_than_or_equal_to: 0 }

end

cars/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cars/app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def edit
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(params.require(:car).permit(:make, :model, :transmission, :year, :cylinders, :mpg, :price, :image))
    if @car.save
      redirect_to cars_path
    else
      render :new
    end

  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  def update
    @car = Car.find(params[:id])

    if @car.update(params.require(:car).permit(:make, :model, :transmission, :year, :cylinders, :mpg, :price, :image))
      redirect_to @car
    else
      render :edit

    end

    #Below is the quickest way to update but with FORBIDDEN FAILURE.
    #fail
    #@car = Car.find(params[:id])
    #@car.update(params[:car])
    #redirect_to @car

  end


end

cars/app/helpers/application_helper.rb
module ApplicationHelper
end

cars/app/helpers/cars_helper.rb
module CarsHelper

  def car_image(car)

    if car.image.blank?
      image_tag("car_placeholder.png", class:"img-fluid d-block")
    else
      image_tag(car.image, class:"img-fluid d-block")
    end

  end

end

cars/app/views/cars/_bulma_docs.html.erb
<!--
	hero:       https://bulma.io/documentation/layout/hero/
	section:    https://bulma.io/documentation/layout/section/
	image:      https://bulma.io/documentation/elements/image/
	columns:    https://bulma.io/documentation/columns/basics/
	media:      https://bulma.io/documentation/layout/media-object/
	icon:       https://bulma.io/documentation/elements/icon/
	breadcrumb: https://bulma.io/documentation/components/breadcrumb/
	level:      https://bulma.io/documentation/layout/level/
-->

<!-- hero: https://bulma.io/documentation/layout/hero/ -->
<section class="hero">
  <div class="hero-body">
    <!-- ... -->
  </div>
</section>

<!-- section: https://bulma.io/documentation/layout/section/ -->
<section class="section">
  <div class="container">
    <!-- ... -->
  </div>
</section>

<!-- image: https://bulma.io/documentation/elements/image/ -->
<figure class="image is-128x128">
  <img src="https://bulma.io/images/placeholders/128x128.png">
</figure>

<!-- columns: https://bulma.io/documentation/columns/basics/ -->
<div class="columns">
  <div class="column">
    <!-- ... -->
  </div>
</div>

<!-- media: https://bulma.io/documentation/layout/media-object/ -->
<article class="media">
  <figure class="media-left">
    <!-- ... -->
  </figure>
  <div class="media-content">
    <div class="content">
      <!-- ... -->
    </div>
  </div>
</article>

<!-- icon: https://bulma.io/documentation/elements/icon/ -->
<span class="icon has-text-success">
	<i class="fas fa-check-square"></i>
</span>

<!-- breadcrumb: https://bulma.io/documentation/components/breadcrumb/ -->
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="#"><!-- ... --></a></li>
    <li class="is-active"><a href="#" aria-current="page"><!-- ... --></a></li>
  </ul>
</nav>

<!-- level: https://bulma.io/documentation/layout/level/ -->
<div class="level">
  <div class="level-item">
    <!-- ... -->
  </div>
</div>

<!-- section: https://bulma.io/documentation/layout/section/ -->
<section class="section">
  <div class="container">
    <!-- ... -->
  </div>
</section>

<!-- section: https://bulma.io/documentation/layout/section/ -->
<section class="section">
  <div class="container">
    <!-- ... -->
  </div>
</section>

cars/app/views/cars/_errors_on_submit.html.erb
<%if @car.errors.any? %>
  <div class="py-5 text-center" >
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="mb-3 text-danger">You Have <%=@car.errors.count %> Errors</h1>
          <ul class="list-group list-group-flush">
            <%@car.errors.full_messages.each do |error| %>
              <li class="list-group-item"><i class="fa mr-2 fa-exclamation-triangle text-danger"></i><%=error %></li>
            <%end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<%end %>

cars/app/views/cars/_form.html.erb
<%=render 'errors_on_submit' %>

<%= form_for(@car) do |f| %>

  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="mx-auto col-lg-6 col-10">
          <h1>Edit Hyundai Kona</h1>
          <p class="mb-3">Make your edits here.</p>
          <form class="text-left">

            <div class="form-group">
              <%=f.label :make %><br>
              <%=f.text_field :make, class:"form-control" %>
            </div>

            <div class="form-group">
              <%=f.label :model %><br>
              <%=f.text_field :model, class:"form-control" %>
            </div>

            <div class="form-group">
              <%=f.label :transmission %><br>
              <%=f.text_field :transmission, class:"form-control" %>
            </div>

            <div class="form-group">
              <%=f.label :year %><br>
              <%=f.text_field :year, class:"form-control" %>
            </div>

            <div class="form-group">
              <%=f.label :cylinders %><br>
              <%=f.number_field :cylinders, class:"form-control" %>
            </div>

            <div class="form-group">
              <%=f.label :mpg %><br>
              <%=f.text_field :mpg, class:"form-control" %>
            </div>

            <div class="form-group">
              <%=f.label :price %><br>
              <%=f.text_field :price, class:"form-control" %>
            </div>

            <div class="form-group">
              <%=f.label :image %><br>
              <%=f.text_field :image, class:"form-control" %>
            </div>

            <%= f.submit class:"btn btn-primary"%>
          </form>
        </div>
      </div>
    </div>
  </div>
<% end %>

cars/app/views/cars/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light">
  <div class="container justify-content-center"> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar3">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse text-center justify-content-center" id="navbar3">
      <ul class="navbar-nav">
        <li class="nav-item mx-2"> <a class="nav-link" href="#">Home</a> </li>
        <li class="nav-item mx-2"> <a class="nav-link" href="#">Placeholder</a> </li>
        <li class="nav-item mx-2"> <a class="nav-link navbar-brand mr-0 text-primary" href="#"><i class="fa d-inline fa-lg fa-stop-circle-o"></i>
          <b> CAR INVENTORY</b></a> </li>
        <li class="nav-item mx-2"> <a class="nav-link" href="#">About</a> </li>
        <li class="nav-item mx-2"> <a class="nav-link" href="#">Placeholder </a> </li>
      </ul>
    </div>
  </div>
</nav>

cars/app/views/cars/edit.html.erb
<%=render 'form' %>




<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<%= form_for(@car) do |f| %>
  <%=f.label :make %><br>
  <%= f.text_field :make %> <br>

  <%=f.label :model %><br>
  <%= f.text_area :model%><br>

  <%= f.submit%>
<% end %>

cars/app/views/cars/index.html.erb
<%=render 'nav' %>

<section>
  <div class="container has-text-centered">
    <h1 class="is-size-1">Car Inventory</h1>
  </div>
</section>

<%@cars.each do |car| %>
  <div class="py-5" >
    <div class="container border">
      <div class="row">
        <div class="col-md-4 d-flex flex-row justify-content-center align-items-center"><%=car_image(car) %></div>
        <div class="col-md-8">
          <h3 class=""><%=car.make%> <%=car.model%></h3>
          <div class="row">
            <div class="col-md-12 d-flex justify-content-start flex-wrap flex-row">
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">Transmission</p>
                  <p><%=car.transmission %></p>
                </div>
              </div>
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">Year</p>
                  <p><%=car.year %></p>
                </div>
              </div>
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">Cylinders</p>
                  <p><%=car.cylinders %></p>
                </div>
              </div>
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">MPG</p>
                  <p><%=car.mpg %></p>
                </div>
              </div>
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">Price</p>
                  <p><%=number_to_currency(car.price) %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead" style="">The Kona isn't perfect, but in a segment full of compromises it offers a great combination of comfort, practicality, fun and technology, all wrapped up in a package that feels firmly put together. </p>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-md-12">
          <div class="btn-group">
            <%=link_to("Full Details", car, class:"btn btn-primary mr-2") %>
            <a href="#" class="btn btn-primary mr-2">Placeholder</a>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end %>



<section>
  <div class="container">

    <%=link_to "Create New Car", new_car_path %>

    <%@cars.each do |car| %>

      <p><strong>Make: </strong> <%=car.make %></p>
      <p><strong>Model: </strong> <%=car.model %></p>
      <p><strong>Transmission: </strong>: <%=car.transmission %></p>
      <p><strong>Year: </strong> <%=car.year %></p>
      <p><strong>MPG: </strong> <%=car.mpg %></p>
      <p><strong>Price: </strong> <%=number_to_currency(car.price) %></p>
      <%=link_to "Details", car %>
      <br>
      <br>

    <% end %>

  </div>
</section>





<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-4 col-lg-3 order-2 order-md-1 p-0"> <img class="img-fluid d-block" src="https://static.pingendo.com/img-placeholder-3.svg"> </div>
          <div class="d-flex flex-column justify-content-center col-md-8 offset-lg-1 align-items-start order-1 order-md-2" style="">
            <h3>Toyota Corolla</h3>
            <p class="mb-3">I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary.</p>
            <div class="list-group">
              <a href="#" class="list-group-item list-group-item-action"><b> Make</b>: Toyota</a>
              <a href="#" class="list-group-item list-group-item-action">Model: Corolla</a>
              <a href="#" class="list-group-item list-group-item-action">Transmission: Auto</a>
              <a href="#" class="list-group-item list-group-item-action">Year: 1996</a>
              <a href="#" class="list-group-item list-group-item-action">MPG: 33</a><a href="#" class="list-group-item list-group-item-action">Price: $38,022</a>
            </div>
            <div class="btn-group mt-2"> <a href="#" class="btn btn-primary">Details</a> <a href="#" class="btn btn-primary">Placeholder</a> <a href="#" class="btn btn-primary">Placeholder</a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="py-5" style="">
  <div class="container">
    <div class="row">
      <div class="col-md-12"></div>
    </div>
  </div>
</div>

cars/app/views/cars/new.html.erb
<%=render 'form' %>>

cars/app/views/cars/show.html.erb
<section>
  <div class="container has-text-centered">
    <h1 class="is-size-1">Show Page</h1>
  </div>
</section>

  <div class="py-5" >
    <div class="container border">
      <div class="row">
        <div class="col-md-4 d-flex flex-row justify-content-center align-items-center"><%=car_image(@car)%></div>
        <div class="col-md-8">
          <h3 class=""><%=@car.make%> <%=@car.model%></h3>
          <div class="row">
            <div class="col-md-12 d-flex justify-content-start flex-wrap flex-row">
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">Transmission</p>
                  <p><%=@car.transmission %></p>
                </div>
              </div>
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">Year</p>
                  <p><%=@car.year %></p>
                </div>
              </div>
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">Cylinders</p>
                  <p><%=@car.cylinders %></p>
                </div>
              </div>
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">MPG</p>
                  <p><%=@car.mpg %></p>
                </div>
              </div>
              <div class="row mr-2">
                <div class="col-md-12">
                  <p class="text-uppercase text-muted mb-0">Price</p>
                  <p><%=number_to_currency(@car.price) %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="lead" style="">The Kona isn't perfect, but in a segment full of compromises it offers a great combination of comfort, practicality, fun and technology, all wrapped up in a package that feels firmly put together. </p>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-md-12">
          <div class="btn-group">
            <%=link_to("All Cars", cars_path, class:"btn btn-primary mr-2") %>
            <%=link_to("Edit", edit_car_path, class:"btn btn-primary mr-2") %>
            <%=link_to("Delete", car_path, method: :delete, class:"btn btn-primary mr-2") %>
            <a href="#" class="btn btn-primary mr-2">Placeholder</a>
          </div>
        </div>
      </div>
    </div>
  </div>







<section>
  <div class="container">
      <p><strong>Make: </strong> <%=@car.make %></p>
      <p><strong>Model: </strong> <%=@car.model %></p>
      <p><strong>Transmission: </strong>: <%=@car.transmission %></p>
      <p><strong>Year: </strong> <%=@car.year %></p>
      <p><strong>MPG: </strong> <%=@car.mpg %></p>
      <p><strong>Price: </strong> <%=number_to_currency(@car.price) %></p>
      <br>
      <%=link_to "All Cars", root_path %>
      <%=link_to "Edit", edit_car_path %>
      <%=link_to "Destroy", car_path(@car), method: :delete %>

      <p>Linking back to text.</p>
  </div>
</section>

cars/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cars</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>